version: '3'
services:
  weibo-web:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always  # 容器退出后总是重启
    expose:
      - "8000"
    volumes:
      - ./config.json:/app/config.json
      - ./weibo:/app/weibo
      - ./log:/app/log

  nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - weibo-web
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
